//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMech
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string PicturePath { get; set; }
        public Nullable<int> ProductionYear { get; set; }
        public string ClassName { get; set; }
    }
}
